#!/usr/bin/env bash
case "$1" in
    upgrade)
        ;;
    purge)
        rm /etc/webhookd.env
        ;;
    *)
        deluser webhookd
        echo "WEBHOOKD user removed"
        ;;
esac

exit 0