#!/usr/bin/env bash
case "$1" in
    upgrade)
        ;;
    purge)
        rm /etc/webhookd.env
        if [ -x "$(command -v deluser)" ]; then
          deluser --quiet --system webhookd > /dev/null || true
        else
          echo >&2 "not removing webhookd system account because deluser command was not found"
        fi
        ;;
    *)
        ;;
esac

exit 0